# Generated by Django 4.2.7 on 2025-12-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('project_code', models.CharField(max_length=20, unique=True, verbose_name='プロジェクトコード')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('PLANNING', '計画中'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了'), ('SUSPENDED', '中止')], default='PLANNING', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='実績開始日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='実績終了日')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='予算')),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='進捗率(%)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('name', models.CharField(max_length=200, verbose_name='マイルストーン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('target_date', models.DateField(verbose_name='目標日')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='達成日')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未達成'), ('ACHIEVED', '達成'), ('DELAYED', '遅延')], default='NOT_STARTED', max_length=20, verbose_name='ステータス')),
                ('criteria', models.TextField(blank=True, verbose_name='達成基準')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'マイルストーン',
                'verbose_name_plural': 'マイルストーン',
                'db_table': 'milestones',
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('project_code', models.CharField(db_index=True, max_length=20, verbose_name='プロジェクトコード')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('PLANNING', '計画中'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了'), ('SUSPENDED', '中止')], default='PLANNING', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='実績開始日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='実績終了日')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='予算')),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='進捗率(%)')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical プロジェクト',
                'verbose_name_plural': 'historical プロジェクト',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('role', models.CharField(choices=[('PM', 'プロジェクトマネージャー'), ('LEADER', 'リーダー'), ('MEMBER', 'メンバー'), ('VIEWER', '閲覧者')], default='MEMBER', max_length=10, verbose_name='役割')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='参加日')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='離脱日')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロジェクトメンバー',
                'verbose_name_plural': 'プロジェクトメンバー',
                'db_table': 'project_members',
                'indexes': [models.Index(fields=['project', 'role'], name='project_mem_project_0d0b7d_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_date'], name='projects_status_4ab905_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='projects_project_cceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'target_date'], name='milestones_project_264193_idx'),
        ),
    ]
