# Generated by Django 4.2.7 on 2025-12-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('task_number', models.CharField(max_length=20, verbose_name='タスク番号')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未着手'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了'), ('ON_HOLD', '保留')], default='NOT_STARTED', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=10, verbose_name='優先度')),
                ('planned_start_date', models.DateField(verbose_name='開始予定日')),
                ('planned_end_date', models.DateField(verbose_name='終了予定日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='開始実績日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='終了実績日')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='見積工数(h)')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='実績工数(h)')),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='進捗率(%)')),
                ('wbs_code', models.CharField(blank=True, max_length=50, verbose_name='WBSコード')),
                ('level', models.IntegerField(default=0, verbose_name='階層レベル')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='親タスク')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'tasks',
                'ordering': ['wbs_code', 'planned_start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'タスクコメント',
                'verbose_name_plural': 'タスクコメント',
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('task_number', models.CharField(max_length=20, verbose_name='タスク番号')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未着手'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了'), ('ON_HOLD', '保留')], default='NOT_STARTED', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=10, verbose_name='優先度')),
                ('planned_start_date', models.DateField(verbose_name='開始予定日')),
                ('planned_end_date', models.DateField(verbose_name='終了予定日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='開始実績日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='終了実績日')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='見積工数(h)')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='実績工数(h)')),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='進捗率(%)')),
                ('wbs_code', models.CharField(blank=True, max_length=50, verbose_name='WBSコード')),
                ('level', models.IntegerField(default=0, verbose_name='階層レベル')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.task', verbose_name='親タスク')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical タスク',
                'verbose_name_plural': 'historical タスク',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', '終了-開始 (FS)'), ('SS', '開始-開始 (SS)'), ('FF', '終了-終了 (FF)'), ('SF', '開始-終了 (SF)')], default='FS', max_length=2, verbose_name='依存タイプ')),
                ('lag_days', models.IntegerField(default=0, verbose_name='遅延日数')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='tasks.task', verbose_name='前提タスク')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='tasks.task', verbose_name='後続タスク')),
            ],
            options={
                'verbose_name': 'タスク依存関係',
                'verbose_name_plural': 'タスク依存関係',
                'db_table': 'task_dependencies',
                'unique_together': {('predecessor', 'successor')},
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_assigne_972e70_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['planned_start_date', 'planned_end_date'], name='tasks_planned_46c818_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'task_number')},
        ),
    ]
