# Generated by Django 4.2.7 on 2025-12-26 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('code', models.CharField(max_length=20, verbose_name='大分類コード')),
                ('name', models.CharField(max_length=100, verbose_name='大分類名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '大分類',
                'verbose_name_plural': '大分類',
                'db_table': 'major_categories',
                'ordering': ['system_category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MinorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('code', models.CharField(max_length=20, verbose_name='中分類コード')),
                ('name', models.CharField(max_length=100, verbose_name='中分類名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '中分類',
                'verbose_name_plural': '中分類',
                'db_table': 'minor_categories',
                'ordering': ['major_category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('code', models.CharField(max_length=20, verbose_name='システムコード')),
                ('name', models.CharField(max_length=100, verbose_name='システム名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'システム分類',
                'verbose_name_plural': 'システム分類',
                'db_table': 'system_categories',
                'ordering': ['project', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='systemcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='systemcategory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_categories', to='projects.project', verbose_name='プロジェクト'),
        ),
        migrations.AddField(
            model_name='systemcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='major_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_categories', to='tasks.majorcategory', verbose_name='大分類'),
        ),
        migrations.AddField(
            model_name='minorcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='system_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_categories', to='tasks.systemcategory', verbose_name='システム名'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='major_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.majorcategory', verbose_name='大分類'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='minor_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.minorcategory', verbose_name='中分類'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='system_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.systemcategory', verbose_name='システム名'),
        ),
        migrations.AddField(
            model_name='task',
            name='major_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.majorcategory', verbose_name='大分類'),
        ),
        migrations.AddField(
            model_name='task',
            name='minor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.minorcategory', verbose_name='中分類'),
        ),
        migrations.AddField(
            model_name='task',
            name='system_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.systemcategory', verbose_name='システム名'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['system_category'], name='tasks_system__7390ad_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['major_category'], name='tasks_major_c_cef6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['minor_category'], name='tasks_minor_c_ce43a9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemcategory',
            index=models.Index(fields=['project', 'order'], name='system_cate_project_6ae747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemcategory',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='minorcategory',
            index=models.Index(fields=['major_category', 'order'], name='minor_categ_major_c_eb98ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minorcategory',
            unique_together={('major_category', 'code')},
        ),
        migrations.AddIndex(
            model_name='majorcategory',
            index=models.Index(fields=['system_category', 'order'], name='major_categ_system__a52bbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='majorcategory',
            unique_together={('system_category', 'code')},
        ),
    ]
